package e

const (
	CACHE_ARTICLE              = "ARTICLE"
	CACHE_TEAM                 = "TEAM"
	CACHE_EVENT                = "EVENT"
	CACHE_EVENT_SIGNCOUNT      = "EVENT:SIGNCOUNT"
	CACHE_EVENT_VIEWCOUNT      = "EVENT:VIEWCOUNT"
	CACHE_EVENT_SUBSCRIBECOUNT = "EVENT:SUBSCRIBECOUNT"
	CACHE_TEAM_VIEWCOUNT       = "TEAM:VIEWCOUNT"
	CACHE_VOTE_LOGCOUNT        = "VOTE:LOGCOUNT"
	CACHE_TAG                  = "TAG"
)
