package e

const (
	SUCCESS        = 200
	ERROR          = 500
	INVALID_PARAMS = 400

	//system 10xxx

	//common 11xxx
	ERROR_UPLOAD_CHECK_IMAGE_FORMAT        = 1101
	ERROR_UPLOAD_CHECK_FILE_PATH_NOT_EMPTY = 1102
	ERROR_COMMON_URL_PARAM_ERROR           = 1103
	ERROR_COMMON_PARAM_GIN_BINDJSON_ERROR  = 1104
	ERROR_COMMON_NO_AUTHORITY_ERROR        = 1105

	//common scene 11xxx
	ERROR_WXACODE_SCENE_ID_ERROR               = 1200
	ERROR_WXACODE_SCENE_NOT_EXIST              = 1201
	ERROR_WXACODE_SCENE_EXPIRES_LIMIT          = 1202
	ERROR_RECOMMEND_POSITION_POSCODE_NOT_EMPTY = 1203
	ERROR_RECOMMEND_POSITION_TITLE_NOT_EMPTY   = 1204
	ERROR_RECOMMEND_POSITION_ID_NOT_EMPTY      = 1205
	ERROR_ADVERTISING_TITLE_NOT_EMPTY          = 1206
	ERROR_ADVERTISING_FILEPATH_NOT_EMPTY       = 1207

	//login 20xxx
	ERROR_AUTH_CHECK_TOKEN_FAIL    = 20001
	ERROR_AUTH_CHECK_TOKEN_TIMEOUT = 20002
	ERROR_AUTH_TOKEN               = 20003
	ERROR_AUTH                     = 20004

	//auth 21xxx
	ERROR_LOGIN_FAIL                          = 21001
	ERROR_LOGIN_NONE                          = 21002
	ERROR_LOGIN_PC_SCAN                       = 21003
	ERROR_ADMIN_LOGIN_USERNAME_EMPTY          = 21004
	ERROR_ADMIN_LOGIN_USERNAME_PASSWORD_ERROR = 21005
	ERROR_ADMIN_CHANGE_PASSWORD_DIFF_ERROR    = 21006

	//User 30xxx
	ERROR_USER_GETINFO_FAIL      = 30001
	ERROR_USER_FOLLOW_PARAMS_ERR = 30002
	ERROR_USER_HAS_FOLLOWED      = 30003
	ERROR_USER_BANNED            = 30004 //账号被禁
	ERROR_USER_NOT_EXIST         = 30005
	ERROR_USER_IS_BLACKED        = 30006

	//Team 40xxx
	ERROR_TEAM_ADD_FAIL                   = 40001
	ERROR_TEAM_TITLE_NOT_EMPTY            = 40002
	ERROR_TEAM_COVER_NOT_EMPTY            = 40003
	ERROR_TEAM_AUTH_TYPE_NOT_EMPTY        = 40004
	ERROR_TEAM_AUTH_LICENSE_NOT_EMPTY     = 40005
	ERROR_TEAM_AUTH_IDCARDPROS_NOT_EMPTY  = 40006
	ERROR_TEAM_AUTH_IDCARDCONS_NOT_EMPTY  = 40007
	ERROR_TEAM_AUTH_DEAL_STATUS_NOT_EMPTY = 40008
	ERROR_TEAM_ALBUM_NAME_NOT_EMPTY       = 40009
	ERROR_TEAM_ALBUM_PHOTO_NOT_EMPTY      = 40010
	ERROR_TEAM_ID_NOT_EMPTY               = 40011
	ERROR_TEAM_KEY_ERROR                  = 40012
	ERROR_TEAM_TRANSFER_PARAM_ERROR       = 40013
	ERROR_TEAM_NOT_EXIST                  = 40014
	ERROR_TEAM_AUTH_CHECKING              = 40015
	ERROR_TEAM_BANNED                     = 40016 //组织被禁
	ERROR_TEAM_MEMBER_SIGN_REPEAT         = 40017
	ERROR_TEAM_LEVEL_MSG_REPEAT           = 40018

	//Event 50xxx
	ERROR_EVENT_ADD_FAIL                        = 50001
	ERROR_EVENT_TITLE_NOT_EMPTY                 = 50002
	ERROR_EVENT_BANNER_NOT_EMPTY                = 50003
	ERROR_EVENT_STARTTIME_NOT_EMPTY             = 50004
	ERROR_EVENT_ENDTIME_NOT_EMPTY               = 50005
	ERROR_EVENT_SIGNINFO_NOT_EMPTY              = 50006
	ERROR_FIELDS_NAME_NOT_EMPTY                 = 50007
	ERROR_EVENT_FEE_TITLE_NOT_EMPTY             = 50008
	ERROR_EVENT_ID_NOT_EMPTY                    = 50009
	ERROR_EVENT_SIGN_SIGNDATA_NOT_EMPTY         = 50010
	ERROR_EVENT_SIGN_SIGNCOUNT_NUM_ERROR        = 50011
	ERROR_EVENT_SIGN_EVENTFEEID_NOT_EMPTY       = 50012
	ERROR_EVENT_SIGN_UPPERLIMIT_OVER            = 50013
	ERROR_EVENT_SIGN_FEE_EVERTLIMIT_ERROR       = 50014
	ERROR_EVENT_SIGN_FEE_UPPERLIMIT_ERROR       = 50015
	ERROR_EVENT_SIGN_FIELD_NOT_EMPTY            = 50016
	ERROR_EVENT_NOT_EXIST                       = 50017
	ERROR_EVENT_WITHDRAWED                      = 50018
	ERROR_EVENT_SIGN_FEE_TOTAL_UPPERLIMIT_ERROR = 50019

	ERROR_SIGNED_END                 = 50020 // 报名已截止
	ERROR_SIGNED_START               = 50021 // 报名未开始
	ERROR_SIGNED_BIRD_END            = 50022 // 早鸟票已截止
	ERROR_SIGNED_RE_SIGNED           = 50023 // 已报名，不能重复报名
	ERROR_SIGNED_IN_BLACK            = 50024 // 组织黑名单，不能报名
	ERROR_SIGNED_NOT_EXISTS          = 50025 // 报名数据不存在
	ERROR_SIGNED_CANNOT_EDIT         = 50026 //  报名不能修改
	ERROR_SIGNED_CANNOT_EDIT_CHECKED = 50027 //  报名已通过审核，不能修改
	ERROR_SIGNED_NOT_FOUND           = 50028 //  报名信息未找到，可能是支付超进被删除了
	ERROR_SETTING_EMPTY              = 50029
	ERROR_SIGNED_NOT_NOT_CHECKED     = 50030 // 报名未审核
	ERROR_SIGNED_NOT_NOT_PAID        = 50031 // 报名未支付

	ERROR_GROUP_ID_NOT_EMPTY              = 50041
	ERROR_EVENT_DELETE_HAS_WITHDRAW_ERROR = 50042
	ERROR_EVENT_SIGNED_NEED_FEE_ERROR = 50043

	//event_spread
	ERROR_EVENT_SPREAD_USER_TYPE_ERROR      = 50101
	ERROR_EVENT_SPREAD_USER_ACTION_ERROR    = 50102
	ERROR_EVENT_SPREAD_USER_RECORD_ID_ERROR = 50103
	ERROR_EVENT_SPREAD_CHANNEL_TITLE_EMPTY  = 50104
	ERROR_EVENT_SPREAD_CHANNEL_ID_EMPTY     = 50105
	ERROR_EVENT_SPREAD_CHANNEL_HAS_JOIN     = 50106

	//event_locale
	ERROR_EVENT_LOCALE_SIGNIN_TITLE_NOT_EMPTY          = 50201
	ERROR_EVENT_LOCALE_SIGNIN_TYPE_ERROR               = 50202
	ERROR_EVENT_LOCALE_SIGNIN_ID_ERROR                 = 50203
	ERROR_EVENT_LOCALE_SIGNIN_NOT_CHECKED              = 50204
	ERROR_EVENT_LOCALE_SIGNIN_NOT_PAID                 = 50205
	ERROR_EVENT_LOCALE_SIGNIN_NOT_EXISTS               = 50206
	ERROR_EVENT_LOCALE_SIGNIN_NOT_SUPPORT_USERSUBMIT   = 50207
	ERROR_EVENT_LOCALE_SIGNIN_USER_NOT_EXISTS          = 50208
	ERROR_EVENT_LOCALE_SIGNIN_NOT_SUPPORT_ADMIN_SUBMIT = 50209
	ERROR_EVENT_LOCALE_SIGNIN_HAS_SIGNINED             = 50210
	ERROR_EVENT_LOCALE_SIGNIN_QRCODE_WRONG             = 50211
	ERROR_EVENT_LOCALE_SIGNIN_NOT_SIGNED               = 50212
	ERROR_EVENT_LOCALE_SIGNIN_NOT_BELONG_TO_THIS       = 50213 //不属于本次签到
	ERROR_EVENT_LOCALE_SIGNIN_PAID_TIMEOUT             = 50214
	ERROR_EVENT_LOCALE_PRIZE_KEY_ERROR                 = 50304
	ERROR_EVENT_LOCALE_PRIZE_ID_ERROR                  = 50305
	ERROR_EVENT_LOCALE_PRIZE_NUM_ERROR                 = 50306

	ERROR_EVENT_LOCALE_VOTE_END_TIME_TOO_SMALL = 50406
	ERROR_EVENT_LOCALE_VOTE_STARTED_NO_EDIT    = 50407
	ERROR_EVENT_LOCALE_VOTE_ID_ERROR           = 50408
	ERROR_EVENT_LOCALE_VOTE_HAS_SUBMIT         = 50409
	ERROR_EVENT_LOCALE_VOTE_IS_NOT_EXIST       = 50410
	ERROR_EVENT_LOCALE_VOTE_UPPERLIMIT         = 50411
	ERROR_EVENT_LOCALE_VOTE_TIME_ERROR         = 50412
	ERROR_EVENT_LOCALE_VOTE_NO_PERMISSION      = 50413
	ERROR_EVENT_LOCALE_VOTE_NOT_SIGNED         = 50414
	ERROR_EVENT_LOCALE_VOTE_HAS_PUBLIC         = 50415

	ERROR_EVENT_LOCALE_QUESTION_INFO_NOT_EMPTY = 50509
	ERROR_EVENT_LOCALE_QUESTION_ID_ERROR       = 50510

	ERROR_EVENT_LOCALE_PSQ_ID_ERROR      = 50611
	ERROR_EVENT_LOCALE_PSQ_TITLE_ERROR   = 50612
	ERROR_EVENT_LOCALE_PSQ_ENDTIME_ERROR = 50613
	ERROR_EVENT_LOCALE_PSQ_CANNOT_EDIT   = 50614
	ERROR_EVENT_LOCALE_PSQ_PARAMS_ERROR  = 50615
	ERROR_EVENT_LOCALE_PSQ_HAS_JOIN      = 50616
	ERROR_EVENT_LOCALE_PSQ_HAS_PUBLIC    = 50617

	ERROR_EVENT_LOCALE_SCREEN_PROCESS_ID_ERROR = 50715

	ERROR_EVENT_LOCALE_CONFIRMATION_TYPE_KEY_ERROR = 50816
	ERROR_EVENT_LOCALE_CONFIRMATION_ID_ERROR       = 50817

	// weixin
	ERROR_WEIXIN_ACCESS_TOKEN = 60001

	//order
	ERROR_ORDER_CREATE_SIGNED = 70001
	ERROR_ORDER_CANNOT_PAY    = 70002

	//withdraw
	ERROR_ORDER_WITHDRAW_REALNAME_ERROR       = 80001
	ERROR_ORDER_WITHDRAW_AMOUNT_ERROR         = 80002
	ERROR_ORDER_WITHDRAW_AMOUNT_SMALL_ERROR   = 80003
	ERROR_ORDER_WITHDRAW_AMOUNT_BIG_ERROR     = 80004
	ERROR_ORDER_WITHDRAW_AMOUNT_GREATER_ERROR = 80005
	ERROR_ORDER_WITHDRAW_EXIST_ERROR          = 80006
	ERROR_ORDER_WITHDRAW_TOO_FAST             = 80007
	ERROR_ORDER_WITHDRAW_TOO_EARLY            = 80008

	//signed
	ERROR_CANCEL_SIGNED_END_ERROR        = 90001
	ERROR_CANCEL_SIGNED_NOT_ALLOW_ERROR  = 90002
	ERROR_CANCEL_SIGNED_SIGNED_END_ERROR = 90003

	ERROR_CHECK_SIGNED_NOPAID_ERROR = 100001

	// redis error
	ERROR_REDIS_ERROR = 110001

	//wechat
	ERROR_WECHAT_ACCESS_TOKEN = 120001
)
