package e

var MsgFlags = map[int]string{
	SUCCESS:                          "ok",
	ERROR:                            "系统异常",
	INVALID_PARAMS:                   "请求参数错误",
	ERROR_LOGIN_FAIL:                 "登录失败",
	ERROR_LOGIN_NONE:                 "未登录",
	ERROR_LOGIN_PC_SCAN:              "扫码登录失败",
	ERROR_ADMIN_LOGIN_USERNAME_EMPTY: "用户名不能为空",
	ERROR_ADMIN_LOGIN_USERNAME_PASSWORD_ERROR:   "用户名密码错误",
	ERROR_ADMIN_CHANGE_PASSWORD_DIFF_ERROR:      "两次密码不一致",
	ERROR_AUTH_CHECK_TOKEN_FAIL:                 "Token鉴权失败",
	ERROR_AUTH_CHECK_TOKEN_TIMEOUT:              "Token已超时",
	ERROR_AUTH_TOKEN:                            "Token生成失败",
	ERROR_AUTH:                                  "Token错误",
	ERROR_USER_GETINFO_FAIL:                     "用户信息获取失败",
	ERROR_USER_FOLLOW_PARAMS_ERR:                "关注参数错误",
	ERROR_USER_HAS_FOLLOWED:                     "已关注，不能重复关注",
	ERROR_USER_BANNED:                           "账号被禁",
	ERROR_USER_NOT_EXIST:                        "用户不存在",
	ERROR_USER_IS_BLACKED:                       "用户已在黑名单中",
	ERROR_UPLOAD_CHECK_IMAGE_FORMAT:             "校验图片错误，图片格式或大小有问题",
	ERROR_UPLOAD_CHECK_FILE_PATH_NOT_EMPTY:      "附件地址不能为空",
	ERROR_COMMON_URL_PARAM_ERROR:                "参数错误",
	ERROR_COMMON_PARAM_GIN_BINDJSON_ERROR:       "参数类型错误",
	ERROR_COMMON_NO_AUTHORITY_ERROR:             "操作权限不够",
	ERROR_TEAM_ADD_FAIL:                         "创建组织出错",
	ERROR_TEAM_TITLE_NOT_EMPTY:                  "组织名称不能为空",
	ERROR_TEAM_COVER_NOT_EMPTY:                  "组织封面不能为空",
	ERROR_TEAM_AUTH_TYPE_NOT_EMPTY:              "组织认证类型不能为空",
	ERROR_TEAM_AUTH_LICENSE_NOT_EMPTY:           "组织营业执照不能为空",
	ERROR_TEAM_AUTH_IDCARDPROS_NOT_EMPTY:        "组织身份证正面不能为空",
	ERROR_TEAM_AUTH_IDCARDCONS_NOT_EMPTY:        "组织身份证反面不能为空",
	ERROR_TEAM_AUTH_DEAL_STATUS_NOT_EMPTY:       "组织审核状态必须选择",
	ERROR_TEAM_AUTH_CHECKING:                    "组织认证中，请等待审核",
	ERROR_TEAM_MEMBER_SIGN_REPEAT:               "已申请加入该组织，请勿重复申请",
	ERROR_TEAM_LEVEL_MSG_REPEAT:                 "该等级或等级名称已存在，请勿重复设置",
	ERROR_TEAM_ALBUM_NAME_NOT_EMPTY:             "组织相册名称不能为空",
	ERROR_TEAM_ALBUM_PHOTO_NOT_EMPTY:            "照片ID不能为空",
	ERROR_TEAM_ID_NOT_EMPTY:                     "组织ID不能为空",
	ERROR_TEAM_KEY_ERROR:                        "组织KEY参数错误",
	ERROR_TEAM_TRANSFER_PARAM_ERROR:             "组织转让参数错误",
	ERROR_TEAM_NOT_EXIST:                        "组织不存在",
	ERROR_EVENT_ADD_FAIL:                        "创建活动出错",
	ERROR_EVENT_TITLE_NOT_EMPTY:                 "活动名称不能为空",
	ERROR_EVENT_BANNER_NOT_EMPTY:                "活动Banner不能为空",
	ERROR_EVENT_STARTTIME_NOT_EMPTY:             "活动开始时间不能为空",
	ERROR_EVENT_ENDTIME_NOT_EMPTY:               "活动结束时间不能为空",
	ERROR_EVENT_SIGNINFO_NOT_EMPTY:              "活动报名字段不能为空",
	ERROR_FIELDS_NAME_NOT_EMPTY:                 "字段名字不能为空",
	ERROR_EVENT_FEE_TITLE_NOT_EMPTY:             "票名不能为空",
	ERROR_EVENT_ID_NOT_EMPTY:                    "活动ID不能为空",
	ERROR_EVENT_SIGN_SIGNDATA_NOT_EMPTY:         "报名内容不能为空",
	ERROR_EVENT_SIGN_SIGNCOUNT_NUM_ERROR:        "请填写正确的报名数量",
	ERROR_EVENT_SIGN_EVENTFEEID_NOT_EMPTY:       "报名票种不能为空",
	ERROR_EVENT_SIGN_UPPERLIMIT_OVER:            "报名已满",
	ERROR_EVENT_SIGN_FEE_UPPERLIMIT_ERROR:       "该类报名费库存不足，请减少数量或选择其它报名费",
	ERROR_EVENT_SIGN_FEE_TOTAL_UPPERLIMIT_ERROR: "报名费已售完",
	ERROR_EVENT_SIGN_FEE_EVERTLIMIT_ERROR:       "超过每人限购数量",
	ERROR_EVENT_SIGN_FIELD_NOT_EMPTY:            "报名必填字段不能为空",
	ERROR_SIGNED_END:                            "活动报名已截止",
	ERROR_SIGNED_START:                          "活动报名未开始",
	ERROR_SIGNED_BIRD_END:                       "早鸟票已过购买截止时间，请选择其它票种",
	ERROR_SIGNED_RE_SIGNED:                      "已报名，不能重复报名",
	ERROR_SIGNED_IN_BLACK:                       "您已被管理员禁止报名",
	ERROR_SIGNED_NOT_EXISTS:                     "您未报名参与该活动，不能进行此操作",
	ERROR_SIGNED_CANNOT_EDIT:                    "管理员不允许修改报名",
	ERROR_SIGNED_CANNOT_EDIT_CHECKED:            "报名已审核，不能修改",
	ERROR_SIGNED_NOT_FOUND:                      "未找到报名信息，支付超时会删除报名，如有需要，请重新报名",
	ERROR_EVENT_WITHDRAWED:                      "活动已提现，不能修改",
	ERROR_SETTING_EMPTY:                         "活动分享设置为空",
	ERROR_SIGNED_NOT_NOT_CHECKED:                "报名未审核",
	ERROR_SIGNED_NOT_NOT_PAID:                   "报名未支付",
	ERROR_EVENT_DELETE_HAS_WITHDRAW_ERROR:       "有提现正在处理中，暂不能删除活动",
	ERROR_EVENT_SIGNED_NEED_FEE_ERROR:           "请选择报名费",

	ERROR_GROUP_ID_NOT_EMPTY: "活动分组参数不正确",

	ERROR_EVENT_NOT_EXIST:                              "活动不存在",
	ERROR_EVENT_SPREAD_USER_TYPE_ERROR:                 "规则类型参数不正确",
	ERROR_EVENT_SPREAD_USER_ACTION_ERROR:               "规则统计维度不正确",
	ERROR_EVENT_SPREAD_USER_RECORD_ID_ERROR:            "推广ID不能为空",
	ERROR_EVENT_SPREAD_CHANNEL_TITLE_EMPTY:             "渠道名称不能为空",
	ERROR_EVENT_SPREAD_CHANNEL_ID_EMPTY:                "渠道ID不能为空",
	ERROR_EVENT_SPREAD_CHANNEL_HAS_JOIN:                "已加入过其他渠道，不能加入多个推广渠道",
	ERROR_EVENT_LOCALE_SIGNIN_TITLE_NOT_EMPTY:          "签到名字不能为空",
	ERROR_EVENT_LOCALE_SIGNIN_TYPE_ERROR:               "签到类型不正确",
	ERROR_EVENT_LOCALE_SIGNIN_ID_ERROR:                 "签到ID参数不正确",
	ERROR_EVENT_LOCALE_SIGNIN_NOT_CHECKED:              "报名未审核，不能签到",
	ERROR_EVENT_LOCALE_SIGNIN_NOT_PAID:                 "报名未支付，不能签到",
	ERROR_EVENT_LOCALE_SIGNIN_PAID_TIMEOUT:             "支付超时",
	ERROR_EVENT_LOCALE_SIGNIN_NOT_EXISTS:               "未找到签到",
	ERROR_EVENT_LOCALE_SIGNIN_NOT_SUPPORT_USERSUBMIT:   "签到不支持用户扫码",
	ERROR_EVENT_LOCALE_SIGNIN_NOT_SUPPORT_ADMIN_SUBMIT: "签到不支持管理员扫码",
	ERROR_EVENT_LOCALE_SIGNIN_USER_NOT_EXISTS:          "用户不在此次签到范围",
	ERROR_EVENT_LOCALE_SIGNIN_HAS_SIGNINED:             "已签到，不能重复签到",
	ERROR_EVENT_LOCALE_SIGNIN_QRCODE_WRONG:             "签到二维码不正确",
	ERROR_EVENT_LOCALE_SIGNIN_NOT_SIGNED:               "未报名",
	ERROR_EVENT_LOCALE_SIGNIN_NOT_BELONG_TO_THIS:       "不属于本次签到",

	ERROR_EVENT_LOCALE_PRIZE_KEY_ERROR:             "抽奖人员范围参数不正确",
	ERROR_EVENT_LOCALE_PRIZE_ID_ERROR:              "抽奖ID不正确",
	ERROR_EVENT_LOCALE_PRIZE_NUM_ERROR:             "抽奖人数不能大于参与人数",
	ERROR_EVENT_LOCALE_VOTE_END_TIME_TOO_SMALL:     "投票截止时间不能小于开始时间",
	ERROR_EVENT_LOCALE_VOTE_STARTED_NO_EDIT:        "投票已经发布不能修改",
	ERROR_EVENT_LOCALE_VOTE_ID_ERROR:               "投票ID参数不正确",
	ERROR_EVENT_LOCALE_VOTE_HAS_SUBMIT:             "已投票不能重复投票",
	ERROR_EVENT_LOCALE_VOTE_IS_NOT_EXIST:           "投票不存在",
	ERROR_EVENT_LOCALE_VOTE_UPPERLIMIT:             "可投票数超过上限",
	ERROR_EVENT_LOCALE_VOTE_TIME_ERROR:             "当前非投票时间",
	ERROR_EVENT_LOCALE_VOTE_NO_PERMISSION:          "您不在可投票名单范围内",
	ERROR_EVENT_LOCALE_VOTE_NOT_SIGNED:             "您未报名，不能投票",
	ERROR_EVENT_LOCALE_VOTE_HAS_PUBLIC:             "投票已发布，不能进行此操作",
	ERROR_EVENT_LOCALE_QUESTION_INFO_NOT_EMPTY:     "提问内容不能为空",
	ERROR_EVENT_LOCALE_QUESTION_ID_ERROR:           "提问ID参数不正确",
	ERROR_EVENT_LOCALE_PSQ_ENDTIME_ERROR:           "问卷截止时间不正确",
	ERROR_EVENT_LOCALE_PSQ_ID_ERROR:                "问卷ID参数不正确",
	ERROR_EVENT_LOCALE_PSQ_TITLE_ERROR:             "问卷标题不能为空",
	ERROR_EVENT_LOCALE_PSQ_CANNOT_EDIT:             "问卷已答卷不能再修改",
	ERROR_EVENT_LOCALE_PSQ_PARAMS_ERROR:            "问卷请求参数有误",
	ERROR_EVENT_LOCALE_PSQ_HAS_JOIN:                "已参与问卷，不能重复答卷",
	ERROR_EVENT_LOCALE_PSQ_HAS_PUBLIC:              "问卷已发布，不能删除",
	ERROR_EVENT_LOCALE_SCREEN_PROCESS_ID_ERROR:     "彩排ID参数不正确",
	ERROR_EVENT_LOCALE_CONFIRMATION_TYPE_KEY_ERROR: "确认函用户范围不正确",
	ERROR_EVENT_LOCALE_CONFIRMATION_ID_ERROR:       "确认函ID参数不正确",


	ERROR_WEIXIN_ACCESS_TOKEN: "微信ACCESS_TOKEN异常",

	ERROR_ORDER_CREATE_SIGNED: "订单创建失败",
	ERROR_ORDER_CANNOT_PAY:    "订单不能再次支付",

	ERROR_ORDER_WITHDRAW_REALNAME_ERROR:       "提现真实姓名不能为空",
	ERROR_ORDER_WITHDRAW_AMOUNT_ERROR:         "提现金额不能为空",
	ERROR_ORDER_WITHDRAW_AMOUNT_SMALL_ERROR:   "提现金额不能小于1元",
	ERROR_ORDER_WITHDRAW_AMOUNT_BIG_ERROR:     "单日提现不能超过5000元",
	ERROR_ORDER_WITHDRAW_EXIST_ERROR:          "您有提现正在处理中，处理结束才能发起新的提现",
	ERROR_ORDER_WITHDRAW_TOO_FAST:             "请控制请求频率，否则系统将封禁您的账号",
	ERROR_ORDER_WITHDRAW_AMOUNT_GREATER_ERROR: "提现金额不能大于可用余额",
	ERROR_ORDER_WITHDRAW_TOO_EARLY:            "活动发起24小时内不能提现",

	ERROR_CANCEL_SIGNED_END_ERROR:        "活动已结束",
	ERROR_CANCEL_SIGNED_NOT_ALLOW_ERROR:  "活动不允许取消报名",
	ERROR_CANCEL_SIGNED_SIGNED_END_ERROR: "活动报名已截止不能取消",

	ERROR_CHECK_SIGNED_NOPAID_ERROR: "报名未支付，暂不能审核",

	ERROR_WXACODE_SCENE_ID_ERROR:               "二维码参数错误",
	ERROR_WXACODE_SCENE_NOT_EXIST:              "非系统内部二维码",
	ERROR_WXACODE_SCENE_EXPIRES_LIMIT:          "此二维码已过期",
	ERROR_RECOMMEND_POSITION_POSCODE_NOT_EMPTY: "推荐位code不能为空",
	ERROR_RECOMMEND_POSITION_TITLE_NOT_EMPTY:   "推荐位标题不能为空",
	ERROR_RECOMMEND_POSITION_ID_NOT_EMPTY:      "推荐位ID不能为空",
	ERROR_ADVERTISING_TITLE_NOT_EMPTY:          "广告标题不能为空",
	ERROR_ADVERTISING_FILEPATH_NOT_EMPTY:       "广告附件不能为空",

	ERROR_REDIS_ERROR: "缓存系统异常",

	ERROR_WECHAT_ACCESS_TOKEN: "系统异常，请重试",
}

// GetMsg get error information based on Code
func GetMsg(code int) string {
	msg, ok := MsgFlags[code]
	if ok {
		return msg
	}

	return MsgFlags[ERROR]
}
